# Site settings
title: dumpleHM - Beautiful Dreamer
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: dumpleHM
user_description: Front-end-Developer
email: hohomiminini@naver.com
twitter_username: dumpleHM
github_username:  dumplehomin
gplus_username:  dumplehomin
disqus_username: dumpleHM

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Javascript
    url: /javascript
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
